### ISSUE TITLE
Brush#getIntersectionPoints for-for-for-if is always true

### ISSUE THREAD

**Issue by kungfooman** [KILLTUBE/corvid#1]
![image](https://user-images.githubusercontent.com/5236548/100592915-0b6e7a80-32f8-11eb-97e5-05999b495e10.png)

**Comment by myuce** [comment]
That function is based on the pseudo code written in the seventh page of the [paper](https://raw.githubusercontent.com/stefanha/map-files/master/MAPFiles.pdf) written by Stefan Hajnoczi. It should not cause any issues since all it does is check if `i`, `j` or `k` are equal to any of the other ones in order to avoid executing `getPlaneIntersection` using the same plane as an argument more than once, so I didn't quite understand what causes VS Code to think that is a problem. Feel free to send a pull request though.

**Comment by myuce** [comment]
Fixed in [this commit](https://github.com/KILLTUBE/corvid/commit/009204aa07e30e4e49ce3160fe962480adc35f69)
