### ISSUE TITLE
Error after generating .map file

### ISSUE THREAD

**Issue by FrozenDragon0** [KILLTUBE/corvid#31]
Started to use the tool now, although after it generates the .map file I get this strange error afterwards and the tool just stops the process: 
![image](https://user-images.githubusercontent.com/18079316/208944470-2496cb4d-bfb2-4308-897c-3b3821865925.png)

Map I'm trying to convert is TF2'S Dustbowl.

**Comment by myuce** [comment]
The issue seems to be fixed after the latest commits. I have tested it with the map you mentioned, and it converted without any crashes. You can use the latest pre-release version to see if it works on your end too.

![image](https://github.com/KILLTUBE/corvid/assets/4535623/cc958021-3fad-4627-96e5-ac6c86fa48d4)
